using System.Collections.Generic;
using System.Text;

namespace Scabra.Rpc.Client
{
    internal class CodeBuilder
    {
        protected const string Autogenerated = @"
            //--------------------------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //--------------------------------------------------------------------------------------------------
            ";

        protected const string GeneratedCodeAttribute = 
            "[global::System.CodeDom.Compiler.GeneratedCode(\"ScabraRpcClientProxyGenerator\", \"\")]";

        private readonly StringBuilder sb = new();

        private int indent;
        private string currentIndent = string.Empty;

        public void Indent()
        {
            indent += 4;
            currentIndent = new(' ', indent);
        }

        public void Dedent()
        {
            indent -= 4;
            currentIndent = new(' ', indent);
        }

        public void BreakLine()
        {
            sb.AppendLine();
        }

        public void AppendIndented(string str)
        {
            sb.Append(' ', indent);
            sb.Append(str);
        }

        public void AppendLine(string str)
        {
            sb.Append(' ', indent);
            sb.AppendLine(str);
        }

        public void Append(string str)
        {
            sb.Append(str);
        }

        public void AppendAndNormalizeMultipleLines(string doc)
        {
            if (string.IsNullOrWhiteSpace(doc))
            {
                return;
            }

            foreach (var line in SplitToLines(doc))
            {
                sb.AppendLine(IndentStr(line));
            }
        }

        private string IndentStr(string str)
        {
            return str.TrimStart().Insert(0, currentIndent);
        }

        public string Build()
        {
            return sb.ToString();
        }

        private IEnumerable<string> SplitToLines(string input)
        {
            if (input == null)
            {
                yield break;
            }

            using var reader = new System.IO.StringReader(input);
            while (reader.ReadLine() is { } line)
            {
                yield return line;
            }
        }
    }
}
