namespace Scabra.Rpc.Client
{
    internal class ProxyAttributeCodeBuilder : CodeBuilder
    {
        public string BuildSourceText()
        {
            AppendAndNormalizeMultipleLines(Autogenerated);

            AppendLine("using System;");
            BreakLine();
            AppendLine($"namespace {GetNamespace()}");

            AppendLine("{");
            Indent();

            AppendLine("[AttributeUsage(AttributeTargets.Class)]");
            AppendLine(GeneratedCodeAttribute);
            AppendLine($"internal class {GetClassName()}: Attribute");
            AppendLine("{");
            AppendLine("}");

            Dedent();
            AppendLine("}");

            return Build();
        }

        public string GetFullyQualifiedAttributeName() => $"{GetNamespace()}.{GetClassName()}";

        public string GetClassName() => "RpcClientProxyAttribute";

        private string GetNamespace() => "Scabra.Rpc.Client";
    }
}
