//HintName: SomeServiceScabraProxy4.g.cs

//--------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using global::Scabra.Researches.Codegen;
using global::System;
using global::System.Buffers;
using global::System.IO;
using Scabra.Researches.Codegen.Laguna;
using Scabra.Rpc.Client;
using Scabra;
using Scabra.Rpc;

namespace Scabra.ProxyGenerator2.Tests
{
    [global::System.CodeDom.Compiler.GeneratedCode("ScabraRpcClientProxyGenerator", "")]
    partial class SomeServiceScabraProxy4
    {
        private readonly IScabraRpcChannel _channel;

        public SomeServiceScabraProxy4(IScabraRpcChannel channel)
        {
            _channel = channel ?? throw new ArgumentNullException(nameof(channel));
        }

        public int DoAddition(int operand1, int operand2)
        {
            var reply = _channel.InvokeMethod<ISomeService, int>("DoAddition", operand1, operand2);

            return reply;
        }

        public int DoAdditionWithArray(Array operand1, IPinnable p, int operand2)
        {
            var reply = _channel.InvokeMethod<ISomeService, int>("DoAdditionWithArray", operand1, p, operand2);

            return reply;
        }

        public int DoAdditionWithFile(FileStream operand1, int operand2)
        {
            var reply = _channel.InvokeMethod<ISomeService, int>("DoAdditionWithFile", operand1, operand2);

            return reply;
        }

        public void MethodWithVoidReturnTypeAndSomeParameters(SomeParameterType parameter1)
        {
            _channel.InvokeMethod<ISomeService>("MethodWithVoidReturnTypeAndSomeParameters", parameter1);
        }

        public void MethodWithVoidReturnTypeAndNoParameters()
        {
            _channel.InvokeMethod<ISomeService>("MethodWithVoidReturnTypeAndNoParameters");
        }
    }
}
