//HintName: RpcClientProxyAttribute.g.cs

//--------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

namespace Scabra.Rpc.Client
{
    [AttributeUsage(AttributeTargets.Class)]
    [global::System.CodeDom.Compiler.GeneratedCode("ScabraRpcClientProxyGenerator", "")]
    internal class RpcClientProxyAttribute: Attribute
    {
    }
}
