//HintName: SomeServiceScabraProxy.g.cs

//--------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using global::System;
using Scabra.Researches.Codegen.Laguna;
using Scabra.Rpc.Client;
using Scabra.Rpc;
using Scabra.Rpc.Client;

namespace Scabra.ProxyGenerator2.Tests
{
    [global::System.CodeDom.Compiler.GeneratedCode("ScabraRpcClientProxyGenerator", "")]
    partial class SomeServiceScabraProxy
    {
        private readonly IScabraRpcChannel _channel;

        public SomeServiceScabraProxy(IScabraRpcChannel channel)
        {
            _channel = channel ?? throw new ArgumentNullException(nameof(channel));
        }

        public int JustDoIt()
        {
            var reply = _channel.InvokeMethod<ISomeOtherService, int>("JustDoIt");

            return reply;
        }
    }
}
