name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Scabra.sln
    - name: Build
      run: dotnet build --no-restore src/Scabra.sln /p:Configuration=Release
    - name: Test
      run: dotnet test --no-build --configuration Release -p:ParallelizeTestCollections=false src/Scabra.Tests/Scabra.Tests.csproj
