name: Release
on:
  release:
    types: [released]

jobs:
 windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash
    - run: echo ${{ steps.get_version.outputs.VERSION }}
    - run: dotnet pack src/Scabra/Scabra.csproj -o . -c Release /p:PackageVersion="${{ steps.get_version.outputs.VERSION }}" /p:Version=${{ steps.get_version.outputs.VERSION }}
    - run: dotnet nuget push *.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NuGetAPIKey }}
      shell: bash
          
